const { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, BorderStyle, AlignmentType } = require('docx');
const fs = require('fs');

const createDoc = () => {
    const spacer = () => new Paragraph({ text: '' });

    const heading = (text, level = HeadingLevel.HEADING_1) => new Paragraph({
        children: [new TextRun({ text, bold: true, size: level === HeadingLevel.HEADING_1 ? 36 : level === HeadingLevel.HEADING_2 ? 28 : 24 })],
        heading: level,
        spacing: { before: 300, after: 150 }
    });

    const para = (text, opts = {}) => new Paragraph({
        children: [new TextRun({ text, size: 22, ...opts })],
        spacing: { after: 100 }
    });

    const bullet = (text, opts = {}) => new Paragraph({
        children: [new TextRun({ text, size: 22, ...opts })],
        bullet: { level: 0 },
        spacing: { after: 60 }
    });

    const subBullet = (text) => new Paragraph({
        children: [new TextRun({ text, size: 20, color: '555555' })],
        bullet: { level: 1 },
        spacing: { after: 40 }
    });

    const code = (text) => new Paragraph({
        children: [new TextRun({ text, size: 20, font: 'Consolas', color: '2563EB' })],
        spacing: { after: 60 },
        indent: { left: 400 }
    });

    const doc = new Document({
        sections: [{
            properties: {},
            children: [
                // ═══════════════════════════════════════════
                // TITLE PAGE
                // ═══════════════════════════════════════════
                new Paragraph({ spacing: { before: 2000 } }),
                new Paragraph({
                    children: [new TextRun({ text: 'PRISM Platform', bold: true, size: 56, color: '6366F1' })],
                    alignment: AlignmentType.CENTER
                }),
                new Paragraph({
                    children: [new TextRun({ text: 'Industry-Grade Upgrade', size: 36, color: '8B5CF6' })],
                    alignment: AlignmentType.CENTER
                }),
                new Paragraph({
                    children: [new TextRun({ text: 'Technical Implementation Documentation', size: 28, color: '64748B' })],
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 800 }
                }),
                new Paragraph({
                    children: [new TextRun({ text: `Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, size: 22, color: '94A3B8' })],
                    alignment: AlignmentType.CENTER
                }),
                new Paragraph({
                    children: [new TextRun({ text: 'Version 2.0 — Major Feature Upgrade', size: 22, color: '94A3B8' })],
                    alignment: AlignmentType.CENTER
                }),

                // ═══════════════════════════════════════════
                // TABLE OF CONTENTS
                // ═══════════════════════════════════════════
                new Paragraph({ children: [], pageBreakBefore: true }),
                heading('Table of Contents'),
                para('1. Executive Summary'),
                para('2. Architecture Overview'),
                para('3. Resume Builder — AI Optimization Fix'),
                para('4. Interview Game — Evaluation System Upgrade'),
                para('5. Technical Interview — Video Call + AI Interviewer'),
                para('6. Group Discussion Rooms — Multi-Party Video'),
                para('7. Socket.io Real-Time Communication'),
                para('8. Technology Stack'),
                para('9. File Change Summary'),
                para('10. Deployment & Testing Guide'),

                // ═══════════════════════════════════════════
                // 1. EXECUTIVE SUMMARY
                // ═══════════════════════════════════════════
                new Paragraph({ children: [], pageBreakBefore: true }),
                heading('1. Executive Summary'),
                para('This document details the industry-grade upgrade of the PRISM (Placement & Interview Readiness, Insights, Skills & Mentorship) platform. The upgrade addresses four critical areas that transform PRISM from a prototype into a production-ready interview preparation system.'),
                spacer(),
                heading('1.1 Problems Addressed', HeadingLevel.HEADING_2),
                bullet('Resume Builder AI Optimize returned raw JSON instead of applying optimized content to form fields'),
                bullet('Created resumes were not persisted to the resume list for future editing'),
                bullet('Interview Game HR round scoring was based on answer character length, not quality'),
                bullet('Technical Interview lacked real-world features: no video call, no collaborative code editor with test cases, no AI fallback'),
                bullet('Group Discussion was text-chat only — needed real-time video conferencing'),
                spacer(),
                heading('1.2 Solutions Implemented', HeadingLevel.HEADING_2),
                bullet('Fixed AI response parsing with structured prompts and sanitization pipeline'),
                bullet('Added auto-save mechanism before preview step'),
                bullet('Replaced length-based scoring with Groq LLM evaluation for HR round'),
                bullet('Built full-featured Technical Interview with PeerJS video, Monaco editor, test case runner, and AI interviewer fallback with hint system'),
                bullet('Implemented multi-party video conferencing in GD Rooms using PeerJS mesh topology (up to 4 video + audio-only overflow)'),

                // ═══════════════════════════════════════════
                // 2. ARCHITECTURE OVERVIEW
                // ═══════════════════════════════════════════
                new Paragraph({ children: [], pageBreakBefore: true }),
                heading('2. Architecture Overview'),
                para('PRISM is a full-stack MERN (MongoDB, Express.js, React, Node.js) application with real-time capabilities powered by Socket.io and peer-to-peer video via PeerJS/WebRTC.'),
                spacer(),
                heading('2.1 System Architecture', HeadingLevel.HEADING_2),
                bullet('Frontend: React 19 + Vite 7 (SPA on port 5173)'),
                bullet('Backend: Express.js + Node.js (API server on port 5000)'),
                bullet('Database: MongoDB Atlas (cloud-hosted)'),
                bullet('Real-time: Socket.io (WebSocket transport)'),
                bullet('Video: PeerJS (WebRTC peer-to-peer mesh)'),
                bullet('AI: Groq SDK (LLaMA 3.1 8B Instant)'),
                bullet('Code Editor: Monaco Editor (VS Code engine)'),
                bullet('Code Execution: Self-hosted Judge0 CE via Docker'),
                spacer(),
                heading('2.2 Data Flow: Interview Video Call', HeadingLevel.HEADING_2),
                para('1. User joins interview room → Socket.io "join-room" event'),
                para('2. Server checks participant count → determines AI or Mentor mode'),
                para('3. If AI mode: Groq API generates coding questions + acts as interviewer'),
                para('4. If Mentor mode: WebRTC video established via PeerJS signaling through Socket.io'),
                para('5. Code changes sync in real-time via Socket.io "code-change" events'),
                para('6. Test cases execute via Judge0 CE (self-hosted code execution engine)'),
                para('7. On end: full AI evaluation with scoring across 5 dimensions'),

                // ═══════════════════════════════════════════
                // 3. RESUME BUILDER FIX
                // ═══════════════════════════════════════════
                new Paragraph({ children: [], pageBreakBefore: true }),
                heading('3. Resume Builder — AI Optimization Fix'),
                spacer(),
                heading('3.1 Root Cause Analysis', HeadingLevel.HEADING_2),
                para('The AI optimize feature used Groq\'s LLaMA 3.1 to generate resume content. Two critical bugs existed:'),
                spacer(),
                para('Bug 1: Raw JSON Display', { bold: true }),
                para('The Groq model returned a JSON object, but the system prompt did not enforce plain-text summary output. The model sometimes returned the entire JSON as the "summary" field, or wrapped skills in compound strings like "Programming languages: Java, Python, C++, JavaScript" instead of individual skill entries.'),
                spacer(),
                para('Bug 2: Resume Not Saved', { bold: true }),
                para('The client-side ResumeBuilder.jsx only saved drafts when the user manually clicked "Save". If they went directly from editing to Preview, the draft was never persisted to MongoDB.'),
                spacer(),
                heading('3.2 Server-Side Fix (resumeBuilder.js)', HeadingLevel.HEADING_2),
                para('Changes to POST /api/resume-builder/generate:'),
                spacer(),
                para('A. Enhanced System Prompt', { bold: true }),
                para('The system prompt now explicitly defines the required JSON structure with CRITICAL RULES:'),
                bullet('"summary" must be a plain text paragraph, NOT a JSON dump'),
                bullet('"skillsOptimized" must be individual skill names like ["Java", "Python"], not long phrases'),
                bullet('Model is instructed to return ONLY valid JSON with no surrounding text'),
                spacer(),
                para('B. Skills Sanitization Pipeline', { bold: true }),
                para('After parsing, a sanitization step processes skillsOptimized:'),
                code('result.skillsOptimized = result.skillsOptimized.flatMap(s => {'),
                code('  if (s.includes(":")) return s.split(":")[1].split(",").map(x => x.trim());'),
                code('  if (s.includes(",")) return s.split(",").map(x => x.trim());'),
                code('  return [s.trim()];'),
                code('}).filter(s => s.length > 0 && s.length < 50);'),
                para('This handles all edge cases: "Programming languages: Java, Python" → ["Java", "Python"]'),
                spacer(),
                para('C. Summary Type Guard', { bold: true }),
                para('Added check: if summary is an object instead of string, stringify it as fallback.'),
                spacer(),
                heading('3.3 Client-Side Fix (ResumeBuilder.jsx)', HeadingLevel.HEADING_2),
                para('Changes to the aiGenerate() function:'),
                spacer(),
                para('A. Proper Field Mapping', { bold: true }),
                bullet('Summary: Applied only if typeof === "string"'),
                bullet('Skills: Filtered to only accept strings under 50 chars'),
                bullet('Experience: Maps AI-generated experienceDescriptions back to matching experience entries by index, applying improved descriptions and optionally updated position titles'),
                spacer(),
                para('B. Auto-Save on Preview', { bold: true }),
                para('When the user clicks "Next" on step 6 (Cover Letter → Preview), saveDraft() is called automatically. This ensures the resume is always persisted before preview.'),
                code('onClick={() => { if (step === 6) saveDraft(); setStep(s => s + 1); }}'),
                spacer(),
                para('C. Success Feedback', { bold: true }),
                para('Added aiSuccess state that shows a green confirmation ("✅ Resume optimized! Summary, skills & experience updated.") or red error message for 5 seconds after AI optimization.'),

                // ═══════════════════════════════════════════
                // 4. INTERVIEW GAME EVALUATION
                // ═══════════════════════════════════════════
                new Paragraph({ children: [], pageBreakBefore: true }),
                heading('4. Interview Game — Evaluation System Upgrade'),
                spacer(),
                heading('4.1 HR Round Scoring Fix', HeadingLevel.HEADING_2),
                para('Previous Implementation (Broken):', { bold: true }),
                code('aiScore = Math.round(hrAnswers.reduce((s,a) => s + (a.response?.length || 0), 0) / 8);'),
                para('This scored HR responses purely by character count divided by 8. A long, rambling response scored higher than a concise, excellent one.'),
                spacer(),
                para('New Implementation:', { bold: true }),
                para('HR answers are now evaluated using the Groq AI evaluateAIInterview endpoint:'),
                bullet('All HR Q&A pairs are formatted as a conversation context'),
                bullet('Sent to POST /api/ai-interview/evaluate with type: "hr"'),
                bullet('Groq returns a structured evaluation with overallScore (0-100)'),
                bullet('Fallback: If AI evaluation fails, score based on answer completeness (how many questions received substantive answers of 30+ characters) rather than total character count'),
                spacer(),
                heading('4.2 GD Evaluation Improvement', HeadingLevel.HEADING_2),
                para('The GD round already used evaluateGroupDiscussion API. The fallback was improved:'),
                bullet('Old fallback: gdUserCount * 15 (crude contribution counting)'),
                bullet('New: AI evaluation result used as primary score, with contribution-based fallback only on API failure'),

                // ═══════════════════════════════════════════
                // 5. TECHNICAL INTERVIEW
                // ═══════════════════════════════════════════
                new Paragraph({ children: [], pageBreakBefore: true }),
                heading('5. Technical Interview — Video Call + AI Interviewer'),
                para('This was the largest change — a complete rewrite of TechnicalInterview.jsx from 219 lines to ~380 lines.'),
                spacer(),
                heading('5.1 Mode Detection: AI vs Mentor', HeadingLevel.HEADING_2),
                para('When a user joins an interview room, the system determines the interview mode:'),
                spacer(),
                para('Detection Logic:', { bold: true }),
                code('socketRef.current.on("room-participants", (p) => {'),
                code('  const hasMentor = p.some(pt => pt.userId !== user._id);'),
                code('  if (hasMentor) setMode("mentor");'),
                code('  else { setMode("ai"); initAIInterviewer(); }'),
                code('});'),
                spacer(),
                para('When the room has only the current user, AI mode activates automatically. If a mentor joins later, the mode switches to "mentor" dynamically.'),
                spacer(),
                heading('5.2 AI Interviewer Implementation', HeadingLevel.HEADING_2),
                para('The AI interviewer uses Groq\'s LLaMA 3.1 through three API endpoints:'),
                bullet('POST /ai-interview/start — Generates first technical question with system prompt defining interviewer persona'),
                bullet('POST /ai-interview/chat — Continues conversation, maintains full conversation context for coherent follow-ups'),
                bullet('POST /ai-interview/evaluate — Final evaluation returning JSON with overallScore, technicalSkill, communication, problemSolving, strengths, improvements, and hire recommendation'),
                spacer(),
                para('The AI asks coding questions. The user selects a problem from the sidebar and writes code in the Monaco editor. The AI can observe the conversation context and ask follow-up questions about the approach, time complexity, and edge cases.'),
                spacer(),
                heading('5.3 Hint System', HeadingLevel.HEADING_2),
                para('When users are struggling, they can request hints via the "Get Hint" button:'),
                spacer(),
                para('Mentor Mode:', { bold: true }),
                para('A hint request message is sent via Socket.io chat: "💡 [HINT REQUEST] I\'m struggling with [problem title]. Can you help me with an approach?"'),
                spacer(),
                para('AI Mode:', { bold: true }),
                para('The AI receives the problem description + current code and generates a hint (approach suggestion, data structure recommendation). The prompt explicitly instructs: "Give a helpful HINT — don\'t give the full solution. Suggest an approach, data structure, or algorithm. Keep it concise."'),
                spacer(),
                para('A 15-second cooldown prevents hint spamming.'),
                spacer(),
                heading('5.4 PeerJS Video Call (240p)', HeadingLevel.HEADING_2),
                para('Video configuration optimized for low bandwidth:'),
                code('navigator.mediaDevices.getUserMedia({'),
                code('  video: { width: 320, height: 240, frameRate: 15 },'),
                code('  audio: audioEnabled'),
                code('});'),
                spacer(),
                para('PeerJS Signaling Flow:', { bold: true }),
                para('1. User clicks "Enable Video" → getUserMedia() captures camera at 240p'),
                para('2. PeerJS instance created → peer.on("open") fires with peer ID'),
                para('3. Peer ID sent to room via Socket.io "session-peer-id" event'),
                para('4. Other participants receive "peer-joined" event → peer.call(remotePeerId, localStream)'),
                para('5. Callee answers with their stream → both video elements display remote feeds'),
                para('6. Video panel appears on the right side of the editor'),
                spacer(),
                heading('5.5 Test Case Runner', HeadingLevel.HEADING_2),
                para('The interview includes a full test case runner identical to the coding round in Interview Game:'),
                bullet('Run Tests: Executes code against all test cases via POST /api/code-execution/run-tests'),
                bullet('Run Custom: Executes code with custom stdin via POST /api/code-execution/run-custom'),
                bullet('Results panel shows pass/fail status per test case with expected vs actual output'),
                bullet('Both mentor and AI can see test results through the shared editor state'),
                spacer(),
                heading('5.6 Evaluation', HeadingLevel.HEADING_2),
                para('"End & Evaluate" button triggers POST /api/ai-interview/evaluate with the full conversation context (AI mode) or code submission data (mentor mode). The evaluation result page shows:'),
                bullet('4 score metrics: Overall, Technical Skill, Communication, Problem Solving'),
                bullet('Hire recommendation badge (Strong Hire / Hire / Maybe / No Hire)'),
                bullet('Detailed feedback paragraph'),
                bullet('Strengths and Improvements lists'),

                // ═══════════════════════════════════════════
                // 6. GD ROOMS VIDEO
                // ═══════════════════════════════════════════
                new Paragraph({ children: [], pageBreakBefore: true }),
                heading('6. Group Discussion Rooms — Multi-Party Video'),
                para('GD Rooms were upgraded from text-only chat to a full video conferencing experience.'),
                spacer(),
                heading('6.1 PeerJS Mesh Topology', HeadingLevel.HEADING_2),
                para('For small group sizes (up to 6 participants), PeerJS mesh topology is used:'),
                bullet('Each participant connects directly to every other participant'),
                bullet('No media server required — all streams are peer-to-peer'),
                bullet('Video capped at 4 simultaneous feeds for performance'),
                bullet('Additional participants receive audio-only streams'),
                spacer(),
                para('Why Mesh over SFU:', { bold: true }),
                para('A Selective Forwarding Unit (SFU) like Mediasoup would provide better scalability but requires dedicated server infrastructure. For GD rooms with 4-6 participants, mesh topology provides adequate quality without additional server costs. The 240p video setting further reduces bandwidth requirements.'),
                spacer(),
                heading('6.2 Video Signaling Protocol', HeadingLevel.HEADING_2),
                para('Custom Socket.io events handle PeerJS signaling for GD rooms:'),
                spacer(),
                para('Events added to socketHandler.js:', { bold: true }),
                bullet('"gd-video-join" — Participant broadcasts their PeerJS peer ID to the room'),
                bullet('"gd-peer-joined" — Existing participants receive new peer ID and initiate calls'),
                bullet('"gd-leave-video" — Cleanup when a participant stops video'),
                bullet('"gd-peer-left" — Notifies room to remove the peer\'s video feed'),
                spacer(),
                para('Server-side tracking:', { bold: true }),
                code('const gdVideoRooms = new Map(); // roomId => [{ peerId, userId, name, socketId }]'),
                para('The server maintains a map of active video peers per GD room. When a new peer joins, the server sends them the list of existing peers so they can initiate calls to each one.'),
                spacer(),
                heading('6.3 Video Grid Layout', HeadingLevel.HEADING_2),
                para('The video grid uses CSS Grid with responsive columns:'),
                code('gridTemplateColumns: remotePeers.length > 1 ? "1fr 1fr" : "1fr"'),
                bullet('1 peer: Full-width single column'),
                bullet('2-4 peers: 2x2 grid layout'),
                bullet('Each video has a name overlay at the bottom'),
                bullet('Mute indicator shown on local video'),
                spacer(),
                heading('6.4 RemoteVideo Component', HeadingLevel.HEADING_2),
                para('A dedicated RemoteVideo React component handles the srcObject assignment for remote streams:'),
                code('const RemoteVideo = ({ stream, name }) => {'),
                code('  const videoRef = useRef(null);'),
                code('  useEffect(() => {'),
                code('    if (videoRef.current && stream) videoRef.current.srcObject = stream;'),
                code('  }, [stream]);'),
                code('  // ... renders <video> element'),
                code('};'),
                para('This is necessary because React cannot set srcObject via JSX attributes — it must be assigned imperatively via a ref.'),

                // ═══════════════════════════════════════════
                // 7. SOCKET.IO
                // ═══════════════════════════════════════════
                new Paragraph({ children: [], pageBreakBefore: true }),
                heading('7. Socket.io Real-Time Communication'),
                para('The Socket.io handler (socketHandler.js) was significantly expanded:'),
                spacer(),
                heading('7.1 Event Categories', HeadingLevel.HEADING_2),
                spacer(),
                para('Interview Room Events:', { bold: true }),
                bullet('"join-room" — Join interview room, receive code sync + participant list'),
                bullet('"leave-room" — Leave room, cleanup participant entry'),
                bullet('"code-change" / "code-update" — Real-time collaborative code editing'),
                bullet('"cursor-change" / "cursor-update" — Cursor position sync (future feature)'),
                spacer(),
                para('WebRTC Signaling:', { bold: true }),
                bullet('"session-peer-id" — Exchange PeerJS IDs for 1:1 video calls'),
                bullet('"offer" / "answer" / "ice-candidate" — Standard WebRTC signaling relay'),
                spacer(),
                para('GD Room Events:', { bold: true }),
                bullet('"join-gd" — Join GD Socket.io room (prefixed "gd-{roomId}")'),
                bullet('"gd-video-join" — Register PeerJS ID for multi-party video'),
                bullet('"gd-leave-video" — Unregister from video room'),
                bullet('"gd-peer-joined" / "gd-peer-left" — Peer presence notifications'),
                bullet('"start-gd" — Start GD timer + auto-alerts at 5min and 1min remaining'),
                spacer(),
                para('Chat:', { bold: true }),
                bullet('"send-message" / "receive-message" — Text chat with username and timestamp'),
                spacer(),
                heading('7.2 Duplicate Prevention', HeadingLevel.HEADING_2),
                para('When a user joins a room, existing entries for the same userId are removed before adding:'),
                code('room.participants = room.participants.filter(p => p.userId !== userId);'),
                code('room.participants.push({ socketId: socket.id, userId, userName });'),
                para('This prevents duplicate entries when a user reconnects after a brief disconnection.'),
                spacer(),
                heading('7.3 Disconnection Cleanup', HeadingLevel.HEADING_2),
                para('On disconnect, the handler cleans up both interview rooms and GD video rooms:'),
                bullet('Removes participant from all interview rooms'),
                bullet('Removes peer from all GD video rooms and emits "gd-peer-left"'),
                bullet('Notifies remaining participants of the departure'),

                // ═══════════════════════════════════════════
                // 8. TECHNOLOGY STACK
                // ═══════════════════════════════════════════
                new Paragraph({ children: [], pageBreakBefore: true }),
                heading('8. Technology Stack'),
                spacer(),
                heading('8.1 Frontend', HeadingLevel.HEADING_2),
                bullet('React 19.2 — UI framework with hooks-based architecture'),
                bullet('Vite 7.3 — Build tool with HMR (Hot Module Replacement)'),
                bullet('Monaco Editor — VS Code engine for code editing'),
                bullet('PeerJS 1.5 — WebRTC abstraction for video calls'),
                bullet('Socket.io Client 4.8 — WebSocket real-time communication'),
                bullet('React Router DOM 7.13 — Client-side routing'),
                bullet('React Icons (FI set) — Feather icon library'),
                bullet('Recharts 3.8 — Data visualization'),
                bullet('docx + file-saver — DOCX generation and download'),
                bullet('html2pdf.js — PDF generation from HTML'),
                bullet('Axios — HTTP client for API calls'),
                spacer(),
                heading('8.2 Backend', HeadingLevel.HEADING_2),
                bullet('Node.js + Express.js — HTTP server and REST API'),
                bullet('Socket.io 4.8 — WebSocket server'),
                bullet('MongoDB + Mongoose — Database and ODM'),
                bullet('Groq SDK — AI inference via LLaMA 3.1 8B Instant'),
                bullet('JWT (jsonwebtoken) — Authentication tokens'),
                bullet('bcryptjs — Password hashing'),
                spacer(),
                heading('8.3 Infrastructure', HeadingLevel.HEADING_2),
                bullet('MongoDB Atlas — Cloud-hosted database'),
                bullet('Judge0 CE (Docker) — Self-hosted code execution engine'),
                bullet('PeerJS Cloud — Free STUN/TURN relay for WebRTC signaling'),

                // ═══════════════════════════════════════════
                // 9. FILE CHANGE SUMMARY
                // ═══════════════════════════════════════════
                new Paragraph({ children: [], pageBreakBefore: true }),
                heading('9. File Change Summary'),
                spacer(),
                heading('9.1 Server-Side Changes', HeadingLevel.HEADING_2),
                spacer(),
                para('server/routes/resumeBuilder.js', { bold: true }),
                bullet('Enhanced AI generate prompt with structured JSON rules'),
                bullet('Added skills sanitization pipeline (splits compound strings)'),
                bullet('Added summary type guard (prevents JSON-as-summary)'),
                spacer(),
                para('server/socket/socketHandler.js', { bold: true }),
                bullet('Added GD video peer tracking (gdVideoRooms Map)'),
                bullet('Added "gd-video-join", "gd-leave-video" events'),
                bullet('Added "gd-peer-joined", "gd-peer-left" broadcast events'),
                bullet('Added "session-peer-id" for tech interview video signaling'),
                bullet('Added "join-session", "end-session" events'),
                bullet('Added duplicate participant prevention'),
                bullet('Added comprehensive disconnect cleanup for video rooms'),
                spacer(),
                heading('9.2 Client-Side Changes', HeadingLevel.HEADING_2),
                spacer(),
                para('client/src/pages/ResumeBuilder.jsx', { bold: true }),
                bullet('Fixed aiGenerate() to properly map summary, skills, and experience descriptions'),
                bullet('Added aiSuccess state for visual feedback'),
                bullet('Added auto-save before preview step'),
                spacer(),
                para('client/src/pages/TechnicalInterview.jsx (Complete Rewrite)', { bold: true }),
                bullet('Added AI/Mentor mode detection based on room participants'),
                bullet('Added PeerJS video call (240p, low bandwidth)'),
                bullet('Added AI interviewer conversation with Groq LLaMA 3.1'),
                bullet('Added hint system (works with both AI and mentor)'),
                bullet('Added test case runner + custom I/O panel'),
                bullet('Added end-of-interview AI evaluation with detailed results'),
                spacer(),
                para('client/src/pages/GDRooms.jsx (Complete Rewrite)', { bold: true }),
                bullet('Added PeerJS multi-party video grid (up to 4 video + audio overflow)'),
                bullet('Added camera/microphone toggle controls'),
                bullet('Added RemoteVideo component for proper stream handling'),
                bullet('Improved chat UI with message bubbles and timestamps'),
                bullet('Added video quality indicator (240p, low bandwidth)'),
                spacer(),
                para('client/src/pages/InterviewGame.jsx', { bold: true }),
                bullet('Fixed HR round: now uses AI evaluation via evaluateAIInterview API'),
                bullet('Improved GD evaluation fallback with completeness-based scoring'),
                spacer(),
                para('client/src/components/Sidebar.jsx', { bold: true }),
                bullet('Added GD Rooms link (mentee + mentor views)'),
                bullet('Added Coding Questions link (mentee view)'),
                bullet('Added FiMessageSquare icon import'),
                spacer(),
                para('client/src/App.jsx', { bold: true }),
                bullet('Added GDRooms import and route (/gd-rooms)'),

                // ═══════════════════════════════════════════
                // 10. DEPLOYMENT & TESTING
                // ═══════════════════════════════════════════
                new Paragraph({ children: [], pageBreakBefore: true }),
                heading('10. Deployment & Testing Guide'),
                spacer(),
                heading('10.1 Prerequisites', HeadingLevel.HEADING_2),
                bullet('Node.js 18+ installed'),
                bullet('MongoDB Atlas connection string configured in server/.env'),
                bullet('Groq API key configured in server/.env (GROQ_API_KEY)'),
                bullet('Docker installed (for Judge0 CE code execution)'),
                spacer(),
                heading('10.2 Starting the Application', HeadingLevel.HEADING_2),
                spacer(),
                para('1. Start MongoDB (Atlas — already cloud-hosted)'),
                spacer(),
                para('2. Start Judge0 CE (Code Execution Engine):', { bold: true }),
                code('docker-compose -f judge0-docker-compose.yml up -d'),
                spacer(),
                para('3. Start Backend Server:', { bold: true }),
                code('cd server && npm run dev'),
                para('Server runs on http://localhost:5000'),
                spacer(),
                para('4. Start Frontend:', { bold: true }),
                code('cd client && npm run dev'),
                para('Client runs on http://localhost:5173'),
                spacer(),
                heading('10.3 Test Credentials', HeadingLevel.HEADING_2),
                para('All accounts use password: password123'),
                spacer(),
                para('Mentors:', { bold: true }),
                bullet('rahul.mentor@prism.dev (Rahul Sharma, Google)'),
                bullet('priya.mentor@prism.dev (Priya Patel, Microsoft)'),
                bullet('vikram.mentor@prism.dev (Vikram Singh, Amazon)'),
                spacer(),
                para('Mentees:', { bold: true }),
                bullet('aditya@prism.dev (Aditya Kumar)'),
                bullet('kavya@prism.dev (Kavya Nair)'),
                bullet('rohan@prism.dev (Rohan Gupta)'),
                spacer(),
                para('Admin:', { bold: true }),
                bullet('admin@prism.dev'),
                spacer(),
                heading('10.4 Testing Checklist', HeadingLevel.HEADING_2),
                spacer(),
                para('Resume Builder:', { bold: true }),
                bullet('[ ] Create new resume → fill personal info → click "AI Optimize" → verify fields update (not JSON)'),
                bullet('[ ] Verify skills appear as individual chips, not compound strings'),
                bullet('[ ] Navigate to Preview → go back to list → verify resume appears in saved drafts'),
                spacer(),
                para('Interview Game:', { bold: true }),
                bullet('[ ] Play HR round → answer questions → submit → verify score is reasonable (not length-based)'),
                bullet('[ ] Play GD round → contribute messages → end → verify evaluation'),
                spacer(),
                para('Technical Interview:', { bold: true }),
                bullet('[ ] Open interview with no mentor → verify AI mode activates'),
                bullet('[ ] Select a coding problem → write code → run tests → verify results'),
                bullet('[ ] Click "Get Hint" → verify AI provides approach hint'),
                bullet('[ ] Enable video → verify camera preview appears'),
                bullet('[ ] Click "End & Evaluate" → verify evaluation page with scores'),
                spacer(),
                para('GD Rooms:', { bold: true }),
                bullet('[ ] Create room → join → verify participant list'),
                bullet('[ ] Click "Join Video" → verify local video preview'),
                bullet('[ ] Send chat messages → verify they appear with timestamps'),
                bullet('[ ] Start GD → verify timer counts down'),
                spacer(),
                spacer(),
                new Paragraph({
                    children: [new TextRun({ text: '— End of Document —', italics: true, color: '94A3B8', size: 20 })],
                    alignment: AlignmentType.CENTER
                })
            ]
        }]
    });

    return doc;
};

const main = async () => {
    const doc = createDoc();
    const buffer = await Packer.toBuffer(doc);
    fs.writeFileSync('PRISM_Technical_Documentation.docx', buffer);
    console.log('✅ Documentation generated: PRISM_Technical_Documentation.docx');
};

main().catch(console.error);
