import { useState, useEffect } from 'react';
import { listArtifacts, downloadArtifact } from '../services/api';
import { FiFolder, FiDownload, FiFileText, FiFile, FiCode } from 'react-icons/fi';
import Reveal from '../components/motion/Reveal';
import PageHero from '../components/ui/PageHero';

// Files generated by the PRISM Copilot (resumes, cover letters, documents).
// Lists GET /api/artifacts; downloads stream through the authenticated
// downloadArtifact helper (JWT in the header, never the URL).

const FORMAT_ICON = { pdf: <FiFileText />, docx: <FiFile />, md: <FiCode /> };

const KIND_LABEL = { resume: 'Resume', cover_letter: 'Cover Letter', document: 'Document' };

const formatSize = (bytes) => {
    if (!bytes && bytes !== 0) return '';
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
};

const Artifacts = () => {
    const [artifacts, setArtifacts] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    const [downloading, setDownloading] = useState(null);

    // Load on mount. `loading` already defaults to true, so we never setState
    // synchronously inside the effect (state changes happen after the await).
    useEffect(() => {
        let active = true;
        (async () => {
            try {
                const { data } = await listArtifacts();
                if (active) setArtifacts(data.artifacts || []);
            } catch (err) {
                if (active) setError(err?.response?.data?.message || 'Could not load your files.');
            } finally {
                if (active) setLoading(false);
            }
        })();
        return () => { active = false; };
    }, []);

    const handleDownload = async (a) => {
        setDownloading(a._id);
        try {
            await downloadArtifact(a._id, `${a.title || 'document'}.${a.format}`);
        } catch (err) {
            setError(err.message || 'Download failed.');
        }
        setDownloading(null);
    };

    return (
        <div className="page">
            <PageHero
                eyebrow="Documents"
                title="Files"
                subtitle="Everything the PRISM Copilot has generated for you — resumes, cover letters and documents."
                icon={<FiFolder />}
            />

            {error && <p style={{ color: 'var(--accent-danger)', fontSize: 13, marginBottom: 16 }} role="alert">{error}</p>}

            {loading ? (
                <div className="page"><div className="spinner" /></div>
            ) : artifacts.length === 0 ? (
                <div className="empty-state">
                    <div className="icon"><FiFolder /></div>
                    <p>No files yet. Ask the PRISM Copilot to generate a resume or document, or export one from My Resume.</p>
                </div>
            ) : (
                <div className="grid grid-3">
                    {artifacts.map((a, i) => (
                        <Reveal as="div" key={a._id} i={i} className="glass-card spotlight">
                            <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 12 }}>
                                <span className="nav-icon" style={{ fontSize: 22, color: 'var(--accent-primary)' }}>
                                    {FORMAT_ICON[a.format] || <FiFile />}
                                </span>
                                <span className="chip" style={{ textTransform: 'uppercase', fontSize: 11 }}>{a.format}</span>
                            </div>
                            <h3 style={{ fontSize: 15, marginBottom: 4, wordBreak: 'break-word' }}>{a.title || 'Untitled'}</h3>
                            <p style={{ color: 'var(--text-muted)', fontSize: 12 }}>
                                {KIND_LABEL[a.kind] || 'Document'}
                                {a.sizeBytes != null && ` • ${formatSize(a.sizeBytes)}`}
                            </p>
                            <p style={{ color: 'var(--text-muted)', fontSize: 11, marginTop: 6 }}>
                                {a.createdAt ? new Date(a.createdAt).toLocaleDateString() : ''}
                            </p>
                            <button
                                className="btn btn-action btn-sm"
                                style={{ marginTop: 14, width: '100%' }}
                                onClick={() => handleDownload(a)}
                                disabled={downloading === a._id}
                            >
                                <FiDownload /> {downloading === a._id ? 'Downloading…' : 'Download'}
                            </button>
                        </Reveal>
                    ))}
                </div>
            )}
        </div>
    );
};

export default Artifacts;
