/**
 * Artifacts API — list and download files generated by the PRISM Copilot.
 *
 *  GET  /api/artifacts           — list caller's artifacts (newest first)
 *  GET  /api/artifacts/:id/download — ownership-checked download
 *
 * Download strategy:
 *   local driver → stream from disk (Content-Disposition: attachment)
 *   s3    driver → redirect to S3 public URL (or CDN base) via 302
 *
 * All routes are JWT-protected via the `protect` middleware.
 */

const express = require('express');
const fs = require('fs');
const path = require('path');
const mongoose = require('mongoose');
const { protect } = require('../middleware/auth');
const Artifact = require('../models/Artifact');
const storage = require('../utils/storage');

const router = express.Router();

const UPLOAD_ROOT = path.join(__dirname, '..', 'uploads');

const MIME_TYPES = {
  pdf:  'application/pdf',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  md:   'text/markdown',
};

function isValidId(id) {
  return mongoose.isValidObjectId(id);
}

// ---------------------------------------------------------------------------
// GET /api/artifacts  — list caller's artifacts, newest first
// ---------------------------------------------------------------------------
router.get('/', protect, async (req, res) => {
  try {
    const userId = req.user._id.toString();
    const artifacts = await Artifact.find({ user: userId })
      .sort({ createdAt: -1 })
      .select('kind title format sizeBytes createdAt')
      .lean();

    // Attach the download URL for each artifact.
    const withUrls = artifacts.map((a) => ({
      ...a,
      url: `/api/artifacts/${a._id}/download`,
    }));

    return res.json({ success: true, artifacts: withUrls });
  } catch (err) {
    console.error('List artifacts error:', err);
    return res.status(500).json({ success: false, message: 'Could not list artifacts' });
  }
});

// ---------------------------------------------------------------------------
// GET /api/artifacts/:id/download  — ownership-checked download
// ---------------------------------------------------------------------------
router.get('/:id/download', protect, async (req, res) => {
  try {
    const { id } = req.params;
    if (!isValidId(id)) {
      return res.status(404).json({ success: false, message: 'Artifact not found' });
    }

    const userId = req.user._id.toString();
    const artifact = await Artifact.findOne({ _id: id, user: userId }).lean();
    if (!artifact) {
      // Return 404 regardless of whether the artifact exists — avoids leaking
      // existence to other users.
      return res.status(404).json({ success: false, message: 'Artifact not found' });
    }

    const contentType = MIME_TYPES[artifact.format] || 'application/octet-stream';
    const safeTitle = artifact.title.replace(/[^a-zA-Z0-9 _-]/g, '').trim() || 'document';
    const filename = `${safeTitle}.${artifact.format}`;

    if (artifact.artifactDriver === 's3') {
      // Build the S3 public URL from the key using the same logic as s3.js.
      const { config } = require('../config/env');
      const s3cfg = config.s3();
      let fileUrl;
      if (s3cfg.publicBaseUrl) {
        fileUrl = `${s3cfg.publicBaseUrl.replace(/\/$/, '')}/${artifact.artifactKey}`;
      } else if (s3cfg.endpoint) {
        fileUrl = `${s3cfg.endpoint.replace(/\/$/, '')}/${s3cfg.bucket}/${artifact.artifactKey}`;
      } else {
        fileUrl = `https://${s3cfg.bucket}.s3.${s3cfg.region}.amazonaws.com/${artifact.artifactKey}`;
      }
      res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
      return res.redirect(302, fileUrl);
    }

    // Local driver — stream from disk.
    const filePath = path.join(UPLOAD_ROOT, artifact.artifactKey);

    // Path traversal guard: resolved path must stay inside UPLOAD_ROOT.
    const resolved = path.resolve(filePath);
    if (!resolved.startsWith(path.resolve(UPLOAD_ROOT))) {
      return res.status(400).json({ success: false, message: 'Invalid artifact key' });
    }

    // Stat the on-disk file: also catches the missing-file case in one call,
    // and gives a Content-Length that matches the bytes we're actually about
    // to stream (DB sizeBytes can drift if the file is replaced manually).
    let stat;
    try {
      stat = await fs.promises.stat(resolved);
    } catch (_) {
      return res.status(404).json({ success: false, message: 'Artifact file not found on disk' });
    }

    res.setHeader('Content-Type', contentType);
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.setHeader('Content-Length', stat.size);

    const stream = fs.createReadStream(resolved);
    stream.on('error', (streamErr) => {
      console.error('Artifact stream error:', streamErr);
      if (!res.headersSent) {
        res.status(500).json({ success: false, message: 'Error reading artifact file' });
      }
    });
    stream.pipe(res);
  } catch (err) {
    console.error('Download artifact error:', err);
    return res.status(500).json({ success: false, message: 'Could not download artifact' });
  }
});

// ---------------------------------------------------------------------------
// DELETE /api/artifacts/:id  — ownership-checked delete (DB row + stored file)
// ---------------------------------------------------------------------------
router.delete('/:id', protect, async (req, res) => {
  try {
    const { id } = req.params;
    if (!isValidId(id)) {
      return res.status(404).json({ success: false, message: 'Artifact not found' });
    }

    const userId = req.user._id.toString();
    const artifact = await Artifact.findOne({ _id: id, user: userId });
    if (!artifact) {
      // 404 regardless of existence — never leak another user's artifacts.
      return res.status(404).json({ success: false, message: 'Artifact not found' });
    }

    // Best-effort remove the stored file; a storage error must NOT block the DB
    // delete (an orphaned blob is recoverable, a dangling DB row is the user-facing bug).
    try {
      await storage.deleteFile(artifact.artifactKey);
    } catch (e) {
      console.error('Artifact file delete error (continuing):', e);
    }

    await Artifact.deleteOne({ _id: id });
    return res.json({ success: true, message: 'File deleted' });
  } catch (err) {
    console.error('Delete artifact error:', err);
    return res.status(500).json({ success: false, message: 'Could not delete artifact' });
  }
});

module.exports = router;
